//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BazaModel", "FK_Stavka_cjenika_ID_cjenika", "Cjenik", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Aplikacija.Cjenik), "Stavka_cjenika", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aplikacija.Stavka_cjenika), true)]
[assembly: EdmRelationshipAttribute("BazaModel", "FK_Račun_ID_klijenta", "Klijent", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Aplikacija.Klijent), "Racun", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aplikacija.Racun), true)]
[assembly: EdmRelationshipAttribute("BazaModel", "FK_Usluga_Mjerna_jedinica", "Mjerna_jedinica", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Aplikacija.Mjerna_jedinica), "Usluga", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aplikacija.Usluga), true)]
[assembly: EdmRelationshipAttribute("BazaModel", "FK_Stavka_računa_ID_računa", "Racun", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Aplikacija.Racun), "Stavka_racuna", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aplikacija.Stavka_racuna), true)]
[assembly: EdmRelationshipAttribute("BazaModel", "FK_Stavka_cjenika_ID_usluge", "Usluga", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Aplikacija.Usluga), "Stavka_cjenika", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aplikacija.Stavka_cjenika), true)]
[assembly: EdmRelationshipAttribute("BazaModel", "FK_Stavka_računa_ID_usluge", "Usluga", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Aplikacija.Usluga), "Stavka_racuna", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aplikacija.Stavka_racuna), true)]

#endregion

namespace Aplikacija
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BazaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BazaEntities object using the connection string found in the 'BazaEntities' section of the application configuration file.
        /// </summary>
        public BazaEntities() : base("name=BazaEntities", "BazaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BazaEntities object.
        /// </summary>
        public BazaEntities(string connectionString) : base(connectionString, "BazaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BazaEntities object.
        /// </summary>
        public BazaEntities(EntityConnection connection) : base(connection, "BazaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Admin> Admin
        {
            get
            {
                if ((_Admin == null))
                {
                    _Admin = base.CreateObjectSet<Admin>("Admin");
                }
                return _Admin;
            }
        }
        private ObjectSet<Admin> _Admin;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cjenik> Cjenik
        {
            get
            {
                if ((_Cjenik == null))
                {
                    _Cjenik = base.CreateObjectSet<Cjenik>("Cjenik");
                }
                return _Cjenik;
            }
        }
        private ObjectSet<Cjenik> _Cjenik;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Crm> Crm
        {
            get
            {
                if ((_Crm == null))
                {
                    _Crm = base.CreateObjectSet<Crm>("Crm");
                }
                return _Crm;
            }
        }
        private ObjectSet<Crm> _Crm;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Klijent> Klijent
        {
            get
            {
                if ((_Klijent == null))
                {
                    _Klijent = base.CreateObjectSet<Klijent>("Klijent");
                }
                return _Klijent;
            }
        }
        private ObjectSet<Klijent> _Klijent;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Mjerna_jedinica> Mjerna_jedinica
        {
            get
            {
                if ((_Mjerna_jedinica == null))
                {
                    _Mjerna_jedinica = base.CreateObjectSet<Mjerna_jedinica>("Mjerna_jedinica");
                }
                return _Mjerna_jedinica;
            }
        }
        private ObjectSet<Mjerna_jedinica> _Mjerna_jedinica;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Racun> Racun
        {
            get
            {
                if ((_Racun == null))
                {
                    _Racun = base.CreateObjectSet<Racun>("Racun");
                }
                return _Racun;
            }
        }
        private ObjectSet<Racun> _Racun;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Stavka_cjenika> Stavka_cjenika
        {
            get
            {
                if ((_Stavka_cjenika == null))
                {
                    _Stavka_cjenika = base.CreateObjectSet<Stavka_cjenika>("Stavka_cjenika");
                }
                return _Stavka_cjenika;
            }
        }
        private ObjectSet<Stavka_cjenika> _Stavka_cjenika;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Stavka_racuna> Stavka_racuna
        {
            get
            {
                if ((_Stavka_racuna == null))
                {
                    _Stavka_racuna = base.CreateObjectSet<Stavka_racuna>("Stavka_racuna");
                }
                return _Stavka_racuna;
            }
        }
        private ObjectSet<Stavka_racuna> _Stavka_racuna;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usluga> Usluga
        {
            get
            {
                if ((_Usluga == null))
                {
                    _Usluga = base.CreateObjectSet<Usluga>("Usluga");
                }
                return _Usluga;
            }
        }
        private ObjectSet<Usluga> _Usluga;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Admin EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdmin(Admin admin)
        {
            base.AddObject("Admin", admin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cjenik EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCjenik(Cjenik cjenik)
        {
            base.AddObject("Cjenik", cjenik);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Crm EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCrm(Crm crm)
        {
            base.AddObject("Crm", crm);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Klijent EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKlijent(Klijent klijent)
        {
            base.AddObject("Klijent", klijent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Mjerna_jedinica EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMjerna_jedinica(Mjerna_jedinica mjerna_jedinica)
        {
            base.AddObject("Mjerna_jedinica", mjerna_jedinica);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Racun EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRacun(Racun racun)
        {
            base.AddObject("Racun", racun);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stavka_cjenika EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStavka_cjenika(Stavka_cjenika stavka_cjenika)
        {
            base.AddObject("Stavka_cjenika", stavka_cjenika);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stavka_racuna EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStavka_racuna(Stavka_racuna stavka_racuna)
        {
            base.AddObject("Stavka_racuna", stavka_racuna);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usluga EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsluga(Usluga usluga)
        {
            base.AddObject("Usluga", usluga);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BazaModel", Name="Admin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Admin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Admin object.
        /// </summary>
        /// <param name="iD_admin">Initial value of the ID_admin property.</param>
        /// <param name="ime">Initial value of the ime property.</param>
        /// <param name="prezime">Initial value of the prezime property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="lozinka">Initial value of the lozinka property.</param>
        public static Admin CreateAdmin(global::System.Int32 iD_admin, global::System.String ime, global::System.String prezime, global::System.String username, global::System.String lozinka)
        {
            Admin admin = new Admin();
            admin.ID_admin = iD_admin;
            admin.ime = ime;
            admin.prezime = prezime;
            admin.username = username;
            admin.lozinka = lozinka;
            return admin;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_admin
        {
            get
            {
                return _ID_admin;
            }
            set
            {
                if (_ID_admin != value)
                {
                    OnID_adminChanging(value);
                    ReportPropertyChanging("ID_admin");
                    _ID_admin = StructuralObject.SetValidValue(value, "ID_admin");
                    ReportPropertyChanged("ID_admin");
                    OnID_adminChanged();
                }
            }
        }
        private global::System.Int32 _ID_admin;
        partial void OnID_adminChanging(global::System.Int32 value);
        partial void OnID_adminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ime
        {
            get
            {
                return _ime;
            }
            set
            {
                OnimeChanging(value);
                ReportPropertyChanging("ime");
                _ime = StructuralObject.SetValidValue(value, false, "ime");
                ReportPropertyChanged("ime");
                OnimeChanged();
            }
        }
        private global::System.String _ime;
        partial void OnimeChanging(global::System.String value);
        partial void OnimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prezime
        {
            get
            {
                return _prezime;
            }
            set
            {
                OnprezimeChanging(value);
                ReportPropertyChanging("prezime");
                _prezime = StructuralObject.SetValidValue(value, false, "prezime");
                ReportPropertyChanged("prezime");
                OnprezimeChanged();
            }
        }
        private global::System.String _prezime;
        partial void OnprezimeChanging(global::System.String value);
        partial void OnprezimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lozinka
        {
            get
            {
                return _lozinka;
            }
            set
            {
                OnlozinkaChanging(value);
                ReportPropertyChanging("lozinka");
                _lozinka = StructuralObject.SetValidValue(value, false, "lozinka");
                ReportPropertyChanged("lozinka");
                OnlozinkaChanged();
            }
        }
        private global::System.String _lozinka;
        partial void OnlozinkaChanging(global::System.String value);
        partial void OnlozinkaChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BazaModel", Name="Cjenik")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cjenik : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cjenik object.
        /// </summary>
        /// <param name="iD_cjenika">Initial value of the ID_cjenika property.</param>
        /// <param name="datum">Initial value of the datum property.</param>
        /// <param name="vazeci">Initial value of the vazeci property.</param>
        public static Cjenik CreateCjenik(global::System.Int32 iD_cjenika, global::System.DateTime datum, global::System.Boolean vazeci)
        {
            Cjenik cjenik = new Cjenik();
            cjenik.ID_cjenika = iD_cjenika;
            cjenik.datum = datum;
            cjenik.vazeci = vazeci;
            return cjenik;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_cjenika
        {
            get
            {
                return _ID_cjenika;
            }
            set
            {
                if (_ID_cjenika != value)
                {
                    OnID_cjenikaChanging(value);
                    ReportPropertyChanging("ID_cjenika");
                    _ID_cjenika = StructuralObject.SetValidValue(value, "ID_cjenika");
                    ReportPropertyChanged("ID_cjenika");
                    OnID_cjenikaChanged();
                }
            }
        }
        private global::System.Int32 _ID_cjenika;
        partial void OnID_cjenikaChanging(global::System.Int32 value);
        partial void OnID_cjenikaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum
        {
            get
            {
                return _datum;
            }
            set
            {
                OndatumChanging(value);
                ReportPropertyChanging("datum");
                _datum = StructuralObject.SetValidValue(value, "datum");
                ReportPropertyChanged("datum");
                OndatumChanged();
            }
        }
        private global::System.DateTime _datum;
        partial void OndatumChanging(global::System.DateTime value);
        partial void OndatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean vazeci
        {
            get
            {
                return _vazeci;
            }
            set
            {
                OnvazeciChanging(value);
                ReportPropertyChanging("vazeci");
                _vazeci = StructuralObject.SetValidValue(value, "vazeci");
                ReportPropertyChanged("vazeci");
                OnvazeciChanged();
            }
        }
        private global::System.Boolean _vazeci;
        partial void OnvazeciChanging(global::System.Boolean value);
        partial void OnvazeciChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Stavka_cjenika_ID_cjenika", "Stavka_cjenika")]
        public EntityCollection<Stavka_cjenika> Stavka_cjenika
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Stavka_cjenika>("BazaModel.FK_Stavka_cjenika_ID_cjenika", "Stavka_cjenika");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Stavka_cjenika>("BazaModel.FK_Stavka_cjenika_ID_cjenika", "Stavka_cjenika", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BazaModel", Name="Crm")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Crm : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Crm object.
        /// </summary>
        /// <param name="iD_CRM">Initial value of the ID_CRM property.</param>
        /// <param name="opis_popusta">Initial value of the opis_popusta property.</param>
        /// <param name="broj_dolazaka">Initial value of the broj_dolazaka property.</param>
        /// <param name="vrijeme_provjere">Initial value of the vrijeme_provjere property.</param>
        public static Crm CreateCrm(global::System.Int32 iD_CRM, global::System.String opis_popusta, global::System.Int32 broj_dolazaka, global::System.Int32 vrijeme_provjere)
        {
            Crm crm = new Crm();
            crm.ID_CRM = iD_CRM;
            crm.opis_popusta = opis_popusta;
            crm.broj_dolazaka = broj_dolazaka;
            crm.vrijeme_provjere = vrijeme_provjere;
            return crm;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_CRM
        {
            get
            {
                return _ID_CRM;
            }
            set
            {
                if (_ID_CRM != value)
                {
                    OnID_CRMChanging(value);
                    ReportPropertyChanging("ID_CRM");
                    _ID_CRM = StructuralObject.SetValidValue(value, "ID_CRM");
                    ReportPropertyChanged("ID_CRM");
                    OnID_CRMChanged();
                }
            }
        }
        private global::System.Int32 _ID_CRM;
        partial void OnID_CRMChanging(global::System.Int32 value);
        partial void OnID_CRMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String opis_popusta
        {
            get
            {
                return _opis_popusta;
            }
            set
            {
                Onopis_popustaChanging(value);
                ReportPropertyChanging("opis_popusta");
                _opis_popusta = StructuralObject.SetValidValue(value, false, "opis_popusta");
                ReportPropertyChanged("opis_popusta");
                Onopis_popustaChanged();
            }
        }
        private global::System.String _opis_popusta;
        partial void Onopis_popustaChanging(global::System.String value);
        partial void Onopis_popustaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 broj_dolazaka
        {
            get
            {
                return _broj_dolazaka;
            }
            set
            {
                Onbroj_dolazakaChanging(value);
                ReportPropertyChanging("broj_dolazaka");
                _broj_dolazaka = StructuralObject.SetValidValue(value, "broj_dolazaka");
                ReportPropertyChanged("broj_dolazaka");
                Onbroj_dolazakaChanged();
            }
        }
        private global::System.Int32 _broj_dolazaka;
        partial void Onbroj_dolazakaChanging(global::System.Int32 value);
        partial void Onbroj_dolazakaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vrijeme_provjere
        {
            get
            {
                return _vrijeme_provjere;
            }
            set
            {
                Onvrijeme_provjereChanging(value);
                ReportPropertyChanging("vrijeme_provjere");
                _vrijeme_provjere = StructuralObject.SetValidValue(value, "vrijeme_provjere");
                ReportPropertyChanged("vrijeme_provjere");
                Onvrijeme_provjereChanged();
            }
        }
        private global::System.Int32 _vrijeme_provjere;
        partial void Onvrijeme_provjereChanging(global::System.Int32 value);
        partial void Onvrijeme_provjereChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BazaModel", Name="Klijent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Klijent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Klijent object.
        /// </summary>
        /// <param name="iD_klijenta">Initial value of the ID_klijenta property.</param>
        /// <param name="ime">Initial value of the ime property.</param>
        /// <param name="prezime">Initial value of the prezime property.</param>
        /// <param name="spol">Initial value of the spol property.</param>
        /// <param name="newsletter">Initial value of the newsletter property.</param>
        public static Klijent CreateKlijent(global::System.Int32 iD_klijenta, global::System.String ime, global::System.String prezime, global::System.String spol, global::System.Boolean newsletter)
        {
            Klijent klijent = new Klijent();
            klijent.ID_klijenta = iD_klijenta;
            klijent.ime = ime;
            klijent.prezime = prezime;
            klijent.spol = spol;
            klijent.newsletter = newsletter;
            return klijent;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_klijenta
        {
            get
            {
                return _ID_klijenta;
            }
            set
            {
                if (_ID_klijenta != value)
                {
                    OnID_klijentaChanging(value);
                    ReportPropertyChanging("ID_klijenta");
                    _ID_klijenta = StructuralObject.SetValidValue(value, "ID_klijenta");
                    ReportPropertyChanged("ID_klijenta");
                    OnID_klijentaChanged();
                }
            }
        }
        private global::System.Int32 _ID_klijenta;
        partial void OnID_klijentaChanging(global::System.Int32 value);
        partial void OnID_klijentaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ime
        {
            get
            {
                return _ime;
            }
            set
            {
                OnimeChanging(value);
                ReportPropertyChanging("ime");
                _ime = StructuralObject.SetValidValue(value, false, "ime");
                ReportPropertyChanged("ime");
                OnimeChanged();
            }
        }
        private global::System.String _ime;
        partial void OnimeChanging(global::System.String value);
        partial void OnimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prezime
        {
            get
            {
                return _prezime;
            }
            set
            {
                OnprezimeChanging(value);
                ReportPropertyChanging("prezime");
                _prezime = StructuralObject.SetValidValue(value, false, "prezime");
                ReportPropertyChanged("prezime");
                OnprezimeChanged();
            }
        }
        private global::System.String _prezime;
        partial void OnprezimeChanging(global::System.String value);
        partial void OnprezimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String spol
        {
            get
            {
                return _spol;
            }
            set
            {
                OnspolChanging(value);
                ReportPropertyChanging("spol");
                _spol = StructuralObject.SetValidValue(value, false, "spol");
                ReportPropertyChanged("spol");
                OnspolChanged();
            }
        }
        private global::System.String _spol;
        partial void OnspolChanging(global::System.String value);
        partial void OnspolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefon
        {
            get
            {
                return _telefon;
            }
            set
            {
                OntelefonChanging(value);
                ReportPropertyChanging("telefon");
                _telefon = StructuralObject.SetValidValue(value, true, "telefon");
                ReportPropertyChanged("telefon");
                OntelefonChanged();
            }
        }
        private global::System.String _telefon;
        partial void OntelefonChanging(global::System.String value);
        partial void OntelefonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean newsletter
        {
            get
            {
                return _newsletter;
            }
            set
            {
                OnnewsletterChanging(value);
                ReportPropertyChanging("newsletter");
                _newsletter = StructuralObject.SetValidValue(value, "newsletter");
                ReportPropertyChanged("newsletter");
                OnnewsletterChanged();
            }
        }
        private global::System.Boolean _newsletter;
        partial void OnnewsletterChanging(global::System.Boolean value);
        partial void OnnewsletterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> broj_dolazaka
        {
            get
            {
                return _broj_dolazaka;
            }
            set
            {
                Onbroj_dolazakaChanging(value);
                ReportPropertyChanging("broj_dolazaka");
                _broj_dolazaka = StructuralObject.SetValidValue(value, "broj_dolazaka");
                ReportPropertyChanged("broj_dolazaka");
                Onbroj_dolazakaChanged();
            }
        }
        private Nullable<global::System.Int32> _broj_dolazaka;
        partial void Onbroj_dolazakaChanging(Nullable<global::System.Int32> value);
        partial void Onbroj_dolazakaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> zadnji_dolazak
        {
            get
            {
                return _zadnji_dolazak;
            }
            set
            {
                Onzadnji_dolazakChanging(value);
                ReportPropertyChanging("zadnji_dolazak");
                _zadnji_dolazak = StructuralObject.SetValidValue(value, "zadnji_dolazak");
                ReportPropertyChanged("zadnji_dolazak");
                Onzadnji_dolazakChanged();
            }
        }
        private Nullable<global::System.DateTime> _zadnji_dolazak;
        partial void Onzadnji_dolazakChanging(Nullable<global::System.DateTime> value);
        partial void Onzadnji_dolazakChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Račun_ID_klijenta", "Racun")]
        public EntityCollection<Racun> Racun
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Racun>("BazaModel.FK_Račun_ID_klijenta", "Racun");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Racun>("BazaModel.FK_Račun_ID_klijenta", "Racun", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BazaModel", Name="Mjerna_jedinica")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mjerna_jedinica : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Mjerna_jedinica object.
        /// </summary>
        /// <param name="iD_mjerne_jedinice">Initial value of the ID_mjerne_jedinice property.</param>
        /// <param name="naziv">Initial value of the Naziv property.</param>
        public static Mjerna_jedinica CreateMjerna_jedinica(global::System.Int32 iD_mjerne_jedinice, global::System.String naziv)
        {
            Mjerna_jedinica mjerna_jedinica = new Mjerna_jedinica();
            mjerna_jedinica.ID_mjerne_jedinice = iD_mjerne_jedinice;
            mjerna_jedinica.Naziv = naziv;
            return mjerna_jedinica;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_mjerne_jedinice
        {
            get
            {
                return _ID_mjerne_jedinice;
            }
            set
            {
                if (_ID_mjerne_jedinice != value)
                {
                    OnID_mjerne_jediniceChanging(value);
                    ReportPropertyChanging("ID_mjerne_jedinice");
                    _ID_mjerne_jedinice = StructuralObject.SetValidValue(value, "ID_mjerne_jedinice");
                    ReportPropertyChanged("ID_mjerne_jedinice");
                    OnID_mjerne_jediniceChanged();
                }
            }
        }
        private global::System.Int32 _ID_mjerne_jedinice;
        partial void OnID_mjerne_jediniceChanging(global::System.Int32 value);
        partial void OnID_mjerne_jediniceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Naziv
        {
            get
            {
                return _Naziv;
            }
            set
            {
                OnNazivChanging(value);
                ReportPropertyChanging("Naziv");
                _Naziv = StructuralObject.SetValidValue(value, false, "Naziv");
                ReportPropertyChanged("Naziv");
                OnNazivChanged();
            }
        }
        private global::System.String _Naziv;
        partial void OnNazivChanging(global::System.String value);
        partial void OnNazivChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Usluga_Mjerna_jedinica", "Usluga")]
        public EntityCollection<Usluga> Usluga
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usluga>("BazaModel.FK_Usluga_Mjerna_jedinica", "Usluga");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usluga>("BazaModel.FK_Usluga_Mjerna_jedinica", "Usluga", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BazaModel", Name="Racun")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Racun : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Racun object.
        /// </summary>
        /// <param name="iD_racuna">Initial value of the ID_racuna property.</param>
        /// <param name="datum">Initial value of the datum property.</param>
        /// <param name="iD_korisnika">Initial value of the ID_korisnika property.</param>
        public static Racun CreateRacun(global::System.Int32 iD_racuna, global::System.DateTime datum, global::System.Int32 iD_korisnika)
        {
            Racun racun = new Racun();
            racun.ID_racuna = iD_racuna;
            racun.datum = datum;
            racun.ID_korisnika = iD_korisnika;
            return racun;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_racuna
        {
            get
            {
                return _ID_racuna;
            }
            set
            {
                if (_ID_racuna != value)
                {
                    OnID_racunaChanging(value);
                    ReportPropertyChanging("ID_racuna");
                    _ID_racuna = StructuralObject.SetValidValue(value, "ID_racuna");
                    ReportPropertyChanged("ID_racuna");
                    OnID_racunaChanged();
                }
            }
        }
        private global::System.Int32 _ID_racuna;
        partial void OnID_racunaChanging(global::System.Int32 value);
        partial void OnID_racunaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datum
        {
            get
            {
                return _datum;
            }
            set
            {
                OndatumChanging(value);
                ReportPropertyChanging("datum");
                _datum = StructuralObject.SetValidValue(value, "datum");
                ReportPropertyChanged("datum");
                OndatumChanged();
            }
        }
        private global::System.DateTime _datum;
        partial void OndatumChanging(global::System.DateTime value);
        partial void OndatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_korisnika
        {
            get
            {
                return _ID_korisnika;
            }
            set
            {
                OnID_korisnikaChanging(value);
                ReportPropertyChanging("ID_korisnika");
                _ID_korisnika = StructuralObject.SetValidValue(value, "ID_korisnika");
                ReportPropertyChanged("ID_korisnika");
                OnID_korisnikaChanged();
            }
        }
        private global::System.Int32 _ID_korisnika;
        partial void OnID_korisnikaChanging(global::System.Int32 value);
        partial void OnID_korisnikaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_klijenta
        {
            get
            {
                return _ID_klijenta;
            }
            set
            {
                OnID_klijentaChanging(value);
                ReportPropertyChanging("ID_klijenta");
                _ID_klijenta = StructuralObject.SetValidValue(value, "ID_klijenta");
                ReportPropertyChanged("ID_klijenta");
                OnID_klijentaChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_klijenta;
        partial void OnID_klijentaChanging(Nullable<global::System.Int32> value);
        partial void OnID_klijentaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Račun_ID_klijenta", "Klijent")]
        public Klijent Klijent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Klijent>("BazaModel.FK_Račun_ID_klijenta", "Klijent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Klijent>("BazaModel.FK_Račun_ID_klijenta", "Klijent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Klijent> KlijentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Klijent>("BazaModel.FK_Račun_ID_klijenta", "Klijent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Klijent>("BazaModel.FK_Račun_ID_klijenta", "Klijent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Stavka_računa_ID_računa", "Stavka_racuna")]
        public EntityCollection<Stavka_racuna> Stavka_racuna
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Stavka_racuna>("BazaModel.FK_Stavka_računa_ID_računa", "Stavka_racuna");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Stavka_racuna>("BazaModel.FK_Stavka_računa_ID_računa", "Stavka_racuna", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BazaModel", Name="Stavka_cjenika")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stavka_cjenika : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Stavka_cjenika object.
        /// </summary>
        /// <param name="iD_stavke">Initial value of the ID_stavke property.</param>
        /// <param name="iD_cjenika">Initial value of the ID_cjenika property.</param>
        /// <param name="iD_usluge">Initial value of the ID_usluge property.</param>
        public static Stavka_cjenika CreateStavka_cjenika(global::System.Int32 iD_stavke, global::System.Int32 iD_cjenika, global::System.Int32 iD_usluge)
        {
            Stavka_cjenika stavka_cjenika = new Stavka_cjenika();
            stavka_cjenika.ID_stavke = iD_stavke;
            stavka_cjenika.ID_cjenika = iD_cjenika;
            stavka_cjenika.ID_usluge = iD_usluge;
            return stavka_cjenika;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_stavke
        {
            get
            {
                return _ID_stavke;
            }
            set
            {
                if (_ID_stavke != value)
                {
                    OnID_stavkeChanging(value);
                    ReportPropertyChanging("ID_stavke");
                    _ID_stavke = StructuralObject.SetValidValue(value, "ID_stavke");
                    ReportPropertyChanged("ID_stavke");
                    OnID_stavkeChanged();
                }
            }
        }
        private global::System.Int32 _ID_stavke;
        partial void OnID_stavkeChanging(global::System.Int32 value);
        partial void OnID_stavkeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_cjenika
        {
            get
            {
                return _ID_cjenika;
            }
            set
            {
                OnID_cjenikaChanging(value);
                ReportPropertyChanging("ID_cjenika");
                _ID_cjenika = StructuralObject.SetValidValue(value, "ID_cjenika");
                ReportPropertyChanged("ID_cjenika");
                OnID_cjenikaChanged();
            }
        }
        private global::System.Int32 _ID_cjenika;
        partial void OnID_cjenikaChanging(global::System.Int32 value);
        partial void OnID_cjenikaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_usluge
        {
            get
            {
                return _ID_usluge;
            }
            set
            {
                OnID_uslugeChanging(value);
                ReportPropertyChanging("ID_usluge");
                _ID_usluge = StructuralObject.SetValidValue(value, "ID_usluge");
                ReportPropertyChanged("ID_usluge");
                OnID_uslugeChanged();
            }
        }
        private global::System.Int32 _ID_usluge;
        partial void OnID_uslugeChanging(global::System.Int32 value);
        partial void OnID_uslugeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Stavka_cjenika_ID_cjenika", "Cjenik")]
        public Cjenik Cjenik
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cjenik>("BazaModel.FK_Stavka_cjenika_ID_cjenika", "Cjenik").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cjenik>("BazaModel.FK_Stavka_cjenika_ID_cjenika", "Cjenik").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cjenik> CjenikReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cjenik>("BazaModel.FK_Stavka_cjenika_ID_cjenika", "Cjenik");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cjenik>("BazaModel.FK_Stavka_cjenika_ID_cjenika", "Cjenik", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Stavka_cjenika_ID_usluge", "Usluga")]
        public Usluga Usluga
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usluga>("BazaModel.FK_Stavka_cjenika_ID_usluge", "Usluga").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usluga>("BazaModel.FK_Stavka_cjenika_ID_usluge", "Usluga").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usluga> UslugaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usluga>("BazaModel.FK_Stavka_cjenika_ID_usluge", "Usluga");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usluga>("BazaModel.FK_Stavka_cjenika_ID_usluge", "Usluga", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BazaModel", Name="Stavka_racuna")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stavka_racuna : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Stavka_racuna object.
        /// </summary>
        /// <param name="iD_stavke">Initial value of the ID_stavke property.</param>
        /// <param name="iD_racuna">Initial value of the ID_racuna property.</param>
        /// <param name="iD_usluge">Initial value of the ID_usluge property.</param>
        public static Stavka_racuna CreateStavka_racuna(global::System.Int32 iD_stavke, global::System.Int32 iD_racuna, global::System.Int32 iD_usluge)
        {
            Stavka_racuna stavka_racuna = new Stavka_racuna();
            stavka_racuna.ID_stavke = iD_stavke;
            stavka_racuna.ID_racuna = iD_racuna;
            stavka_racuna.ID_usluge = iD_usluge;
            return stavka_racuna;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_stavke
        {
            get
            {
                return _ID_stavke;
            }
            set
            {
                if (_ID_stavke != value)
                {
                    OnID_stavkeChanging(value);
                    ReportPropertyChanging("ID_stavke");
                    _ID_stavke = StructuralObject.SetValidValue(value, "ID_stavke");
                    ReportPropertyChanged("ID_stavke");
                    OnID_stavkeChanged();
                }
            }
        }
        private global::System.Int32 _ID_stavke;
        partial void OnID_stavkeChanging(global::System.Int32 value);
        partial void OnID_stavkeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_racuna
        {
            get
            {
                return _ID_racuna;
            }
            set
            {
                OnID_racunaChanging(value);
                ReportPropertyChanging("ID_racuna");
                _ID_racuna = StructuralObject.SetValidValue(value, "ID_racuna");
                ReportPropertyChanged("ID_racuna");
                OnID_racunaChanged();
            }
        }
        private global::System.Int32 _ID_racuna;
        partial void OnID_racunaChanging(global::System.Int32 value);
        partial void OnID_racunaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_usluge
        {
            get
            {
                return _ID_usluge;
            }
            set
            {
                OnID_uslugeChanging(value);
                ReportPropertyChanging("ID_usluge");
                _ID_usluge = StructuralObject.SetValidValue(value, "ID_usluge");
                ReportPropertyChanged("ID_usluge");
                OnID_uslugeChanged();
            }
        }
        private global::System.Int32 _ID_usluge;
        partial void OnID_uslugeChanging(global::System.Int32 value);
        partial void OnID_uslugeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Stavka_računa_ID_računa", "Racun")]
        public Racun Racun
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racun>("BazaModel.FK_Stavka_računa_ID_računa", "Racun").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racun>("BazaModel.FK_Stavka_računa_ID_računa", "Racun").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Racun> RacunReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Racun>("BazaModel.FK_Stavka_računa_ID_računa", "Racun");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Racun>("BazaModel.FK_Stavka_računa_ID_računa", "Racun", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Stavka_računa_ID_usluge", "Usluga")]
        public Usluga Usluga
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usluga>("BazaModel.FK_Stavka_računa_ID_usluge", "Usluga").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usluga>("BazaModel.FK_Stavka_računa_ID_usluge", "Usluga").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usluga> UslugaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usluga>("BazaModel.FK_Stavka_računa_ID_usluge", "Usluga");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usluga>("BazaModel.FK_Stavka_računa_ID_usluge", "Usluga", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BazaModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BazaModel", Name="Usluga")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usluga : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usluga object.
        /// </summary>
        /// <param name="iD_usluge">Initial value of the ID_usluge property.</param>
        /// <param name="naziv">Initial value of the naziv property.</param>
        /// <param name="iD_mjerne_jedinice">Initial value of the ID_mjerne_jedinice property.</param>
        /// <param name="cijena">Initial value of the cijena property.</param>
        public static Usluga CreateUsluga(global::System.Int32 iD_usluge, global::System.String naziv, global::System.Int32 iD_mjerne_jedinice, global::System.Decimal cijena)
        {
            Usluga usluga = new Usluga();
            usluga.ID_usluge = iD_usluge;
            usluga.naziv = naziv;
            usluga.ID_mjerne_jedinice = iD_mjerne_jedinice;
            usluga.cijena = cijena;
            return usluga;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_usluge
        {
            get
            {
                return _ID_usluge;
            }
            set
            {
                if (_ID_usluge != value)
                {
                    OnID_uslugeChanging(value);
                    ReportPropertyChanging("ID_usluge");
                    _ID_usluge = StructuralObject.SetValidValue(value, "ID_usluge");
                    ReportPropertyChanged("ID_usluge");
                    OnID_uslugeChanged();
                }
            }
        }
        private global::System.Int32 _ID_usluge;
        partial void OnID_uslugeChanging(global::System.Int32 value);
        partial void OnID_uslugeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String naziv
        {
            get
            {
                return _naziv;
            }
            set
            {
                OnnazivChanging(value);
                ReportPropertyChanging("naziv");
                _naziv = StructuralObject.SetValidValue(value, false, "naziv");
                ReportPropertyChanged("naziv");
                OnnazivChanged();
            }
        }
        private global::System.String _naziv;
        partial void OnnazivChanging(global::System.String value);
        partial void OnnazivChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String opis
        {
            get
            {
                return _opis;
            }
            set
            {
                OnopisChanging(value);
                ReportPropertyChanging("opis");
                _opis = StructuralObject.SetValidValue(value, true, "opis");
                ReportPropertyChanged("opis");
                OnopisChanged();
            }
        }
        private global::System.String _opis;
        partial void OnopisChanging(global::System.String value);
        partial void OnopisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_mjerne_jedinice
        {
            get
            {
                return _ID_mjerne_jedinice;
            }
            set
            {
                OnID_mjerne_jediniceChanging(value);
                ReportPropertyChanging("ID_mjerne_jedinice");
                _ID_mjerne_jedinice = StructuralObject.SetValidValue(value, "ID_mjerne_jedinice");
                ReportPropertyChanged("ID_mjerne_jedinice");
                OnID_mjerne_jediniceChanged();
            }
        }
        private global::System.Int32 _ID_mjerne_jedinice;
        partial void OnID_mjerne_jediniceChanging(global::System.Int32 value);
        partial void OnID_mjerne_jediniceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cijena
        {
            get
            {
                return _cijena;
            }
            set
            {
                OncijenaChanging(value);
                ReportPropertyChanging("cijena");
                _cijena = StructuralObject.SetValidValue(value, "cijena");
                ReportPropertyChanged("cijena");
                OncijenaChanged();
            }
        }
        private global::System.Decimal _cijena;
        partial void OncijenaChanging(global::System.Decimal value);
        partial void OncijenaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Usluga_Mjerna_jedinica", "Mjerna_jedinica")]
        public Mjerna_jedinica Mjerna_jedinica
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mjerna_jedinica>("BazaModel.FK_Usluga_Mjerna_jedinica", "Mjerna_jedinica").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mjerna_jedinica>("BazaModel.FK_Usluga_Mjerna_jedinica", "Mjerna_jedinica").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Mjerna_jedinica> Mjerna_jedinicaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mjerna_jedinica>("BazaModel.FK_Usluga_Mjerna_jedinica", "Mjerna_jedinica");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Mjerna_jedinica>("BazaModel.FK_Usluga_Mjerna_jedinica", "Mjerna_jedinica", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Stavka_cjenika_ID_usluge", "Stavka_cjenika")]
        public EntityCollection<Stavka_cjenika> Stavka_cjenika
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Stavka_cjenika>("BazaModel.FK_Stavka_cjenika_ID_usluge", "Stavka_cjenika");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Stavka_cjenika>("BazaModel.FK_Stavka_cjenika_ID_usluge", "Stavka_cjenika", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BazaModel", "FK_Stavka_računa_ID_usluge", "Stavka_racuna")]
        public EntityCollection<Stavka_racuna> Stavka_racuna
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Stavka_racuna>("BazaModel.FK_Stavka_računa_ID_usluge", "Stavka_racuna");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Stavka_racuna>("BazaModel.FK_Stavka_računa_ID_usluge", "Stavka_racuna", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
